In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import warnings
from sklearn.neighbors import KNeighborsClassifier

warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r"C:\Users\ADMIN\Documents\카카오톡 받은 파일\car.data")

In [3]:
data

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [5]:
data.columns

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [6]:
data.isnull().sum()

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in data.columns:
    data[i] = le.fit_transform(data[i])
    
# 문자를 숫자로 바꿔주는 코드

In [8]:
data

vhigh  vhigh.1  2  2.1  small  low  unacc
0         3        3  0    0      2    2      2
1         3        3  0    0      2    0      2
2         3        3  0    0      1    1      2
3         3        3  0    0      1    2      2
4         3        3  0    0      1    0      2
...     ...      ... ..  ...    ...  ...    ...
1722      1        1  3    2      1    2      1
1723      1        1  3    2      1    0      3
1724      1        1  3    2      0    1      2
1725      1        1  3    2      0    2      1
1726      1        1  3    2      0    0      3

[1727 rows x 7 columns]

In [10]:
X=data.drop('vhigh',axis=1)
X.head()

vhigh.1  2  2.1  small  low  unacc
0        3  0    0      2    2      2
1        3  0    0      2    0      2
2        3  0    0      1    1      2
3        3  0    0      1    2      2
4        3  0    0      1    0      2

In [11]:
y = data['vhigh']
y.head()

0    3
1    3
2    3
3    3
4    3
Name: vhigh, dtype: int32

In [27]:
data.shape

(1727, 7)

In [12]:
from sklearn.model_selection import train_test_split
X = data.iloc[:,0:6].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

In [28]:
X

array([[3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       [3, 3, 0, 0, 1, 1],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [29]:
Y

array([[0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       ...,
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]], dtype=uint8)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [38]:
from keras import models
from keras import layers
from keras.optimizers import SGD,Adam

#model = Model(inputs=inputs, outputs=output)
def build_model(): 
    model = models.Sequential()
    model.add(layers.Dense(44, activation='relu', input_shape=(6,)))
    model.add(layers.Dense(30, activation='relu'))
    model.add(layers.Dense(20, activation='relu'))
    model.add(layers.Dense(16, activation='relu'))
    model.add(layers.Dense(4, activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.0047), metrics=['accuracy'])
    
    return model


model = build_model() 

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 44)                308       
                                                                 
 dense_6 (Dense)             (None, 30)                1350      
                                                                 
 dense_7 (Dense)             (None, 20)                620       
                                                                 
 dense_8 (Dense)             (None, 16)                336       
                                                                 
 dense_9 (Dense)             (None, 4)                 68        
                                                                 
Total params: 2,682
Trainable params: 2,682
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.001), metrics=['accuracy'])

In [40]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
44/44 [==============================] - 1s 11ms/step - loss: 1.3219 - accuracy: 0.4127 - val_loss: 1.2064 - val_accuracy: 0.4913
Epoch 2/100
44/44 [==============================] - 0s 4ms/step - loss: 0.9494 - accuracy: 0.5525 - val_loss: 0.6605 - val_accuracy: 0.7890
Epoch 3/100
44/44 [==============================] - 0s 4ms/step - loss: 0.4212 - accuracy: 0.9160 - val_loss: 0.2677 - val_accuracy: 0.9191
Epoch 4/100
44/44 [==============================] - 0s 4ms/step - loss: 0.1704 - accuracy: 0.9551 - val_loss: 0.1630 - val_accuracy: 0.9277
Epoch 5/100
44/44 [==============================] - 0s 4ms/step - loss: 0.0965 - accuracy: 0.9761 - val_loss: 0.1026 - val_accuracy: 0.9624
Epoch 6/100
44/44 [==============================] - 0s 4ms/step - loss: 0.0641 - accuracy: 0.9812 - val_loss: 0.0767 - val_accuracy: 0.9682
Epoch 7/100
44/44 [==============================] - 0s 4ms/step - loss: 0.0474 - accuracy: 0.9841 - val_loss: 0.0551 - val_accuracy: 0.9827
Epoch 8/100


44/44 [==============================] - 0s 4ms/step - loss: 1.1179e-04 - accuracy: 1.0000 - val_loss: 2.3816e-04 - val_accuracy: 1.0000
Epoch 58/100
44/44 [==============================] - 0s 4ms/step - loss: 1.0747e-04 - accuracy: 1.0000 - val_loss: 2.3160e-04 - val_accuracy: 1.0000
Epoch 59/100
44/44 [==============================] - 0s 5ms/step - loss: 1.0119e-04 - accuracy: 1.0000 - val_loss: 2.1727e-04 - val_accuracy: 1.0000
Epoch 60/100
44/44 [==============================] - 0s 4ms/step - loss: 9.7099e-05 - accuracy: 1.0000 - val_loss: 2.0798e-04 - val_accuracy: 1.0000
Epoch 61/100
44/44 [==============================] - 0s 4ms/step - loss: 9.3095e-05 - accuracy: 1.0000 - val_loss: 2.0218e-04 - val_accuracy: 1.0000
Epoch 62/100
44/44 [==============================] - 0s 4ms/step - loss: 8.8924e-05 - accuracy: 1.0000 - val_loss: 1.9271e-04 - val_accuracy: 1.0000
Epoch 63/100
44/44 [==============================] - 0s 4ms/step - loss: 8.5168e-05 - accuracy: 1.0000 - val_los

In [41]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        83
           1       1.00      1.00      1.00        87
           2       1.00      1.00      1.00        91
           3       1.00      1.00      1.00        85

    accuracy                           1.00       346
   macro avg       1.00      1.00      1.00       346
weighted avg       1.00      1.00      1.00       346

[[83  0  0  0]
 [ 0 87  0  0]
 [ 0  0 91  0]
 [ 0  0  0 85]]
